
my @data;
my $count=0;

while(<>) {
    if (/Generated by Opal 0.11.0.dev/) 
    {
	#warn $_;
	$count ++;
	open OUT, ">output_${count}.js";
	print OUT "var Opal = require('opal.js');\n";
	print OUT join("\n",@data);
	close OUT;
	@data = ();
    }
    else {
	push @data, $_;
    }
}
